<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Model;

class Math
{
    const PRECISION = 4;

    /**
     * @param float|int|string $leftOperand
     * @param float|int|string $rightOperand
     * @param int $precision
     * @return string
     */
    public function multiply($leftOperand, $rightOperand, $precision = self::PRECISION)
    {
        return bcmul((string)$leftOperand, (string)$rightOperand, $precision);
    }

    /**
     * @param float|int|string $leftOperand
     * @param float|int|string $rightOperand
     * @param int $precision
     * @return string
     */
    public function add($leftOperand, $rightOperand, $precision = self::PRECISION)
    {
        return bcadd((string)$leftOperand, (string)$rightOperand, $precision);
    }

    /**
     * @param float|int|string $leftOperand
     * @param float|int|string $rightOperand
     * @param int $precision
     * @return string
     */
    public function divide($leftOperand, $rightOperand, $precision = self::PRECISION)
    {
        return bcdiv((string)$leftOperand, (string)$rightOperand, $precision);
    }

    /**
     * @param float|int|string $leftOperand
     * @param float|int|string $rightOperand
     * @param int $precision
     * @return string
     */
    public function subtract($leftOperand, $rightOperand, $precision = self::PRECISION)
    {
        return bcsub((string)$leftOperand, (string)$rightOperand, $precision);
    }
}
