<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Model;

use Shipay\PixQrGateway\Api\WalletsRepositoryInterface;
use Shipay\PixQrGateway\Gateway\Http\GetWallets;

class WalletsRepository implements WalletsRepositoryInterface
{
    /**
     * @var GetWallets
     */
    private $getWallets;

    /**
     * @var Wallet
     */
    private $wallet;

    /**
     * WalletsRepository constructor.
     * @param GetWallets $getWallets
     * @param Wallet $wallet
     */
    public function __construct(
        GetWallets $getWallets,
        Wallet $wallet
    ) {
        $this->getWallets = $getWallets;
        $this->wallet = $wallet;
    }

    /**
     * @inheritDoc
     */
    public function getWallets()
    {
        try {
            $wallets = $this->getWallets->placeRequest();
        } catch (\Exception $exception) {
            return [];
        }

        if (empty($wallets) || !isset($wallets[self::WALLETS])) {
            return [];
        }

        $enabledWallets = array_filter($wallets[self::WALLETS], function ($item) {
            return isset($item['active']) && $item['active'] === true;
        });

        return array_reduce($enabledWallets, function ($accumulator, $item) {
            $accumulator[] = [
                'value' => $item['name'],
                'label' => $this->wallet->getWalletLabel($item['name'])
            ];
            return $accumulator;
        }, []);
    }
}
