<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Model;

class Wallet
{
    const AME = 'ame';
    const CIELO = 'cielo';
    const MERCADOPAGO = 'mercadopago';
    const PICPAY = 'picpay';
    const PIX = 'pix';
    const PAGBANK = 'pagbank';
    const SHIPAY_PAGADOR = 'shipay-pagador';

    /**
     * @var array
     */
    private $walletLabelsMapper = [
        self::AME => 'Ame',
        self::CIELO => 'Cielo',
        self::MERCADOPAGO => 'Mercado Pago',
        self::PICPAY => 'Picpay',
        self::PIX => 'PIX',
        self::PAGBANK => 'PagBank',
        self::SHIPAY_PAGADOR => "Shipay Pagador"
    ];

    /**
     * @param string $wallet
     * @return string
     */
    public function getWalletLabel($wallet)
    {
        return $this->walletLabelsMapper[$wallet] ?? $wallet;
    }
}
