<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 */

namespace Shipay\PixQrGateway\Gateway\Request\Builder;

use Magento\Payment\Gateway\Data\PaymentDataObjectInterface;
use Magento\Payment\Gateway\Request\BuilderInterface;
use Magento\Sales\Api\Data\OrderInterface;
use Shipay\PixQrGateway\Gateway\Request\RequestFieldsInterface;

class Buyer implements BuilderInterface
{
    /**
     * @inheritDoc
     */
    public function build(array $buildSubject)
    {
        /** @var PaymentDataObjectInterface $paymentDataObject */
        $paymentDataObject = $buildSubject['payment'];

        /** @var OrderInterface $order */
        $order = $paymentDataObject->getPayment()->getOrder();

        $data = [
            RequestFieldsInterface::BUYER => [
                RequestFieldsInterface::FIRST_NAME => $order->getCustomerFirstname(),
                RequestFieldsInterface::LAST_NAME => $order->getCustomerLastname(),
                RequestFieldsInterface::CPF => $order->getCustomerTaxvat(),
                RequestFieldsInterface::EMAIL => $order->getCustomerEmail(),
                RequestFieldsInterface::PHONE => $order->getBillingAddress()->getTelephone()
            ]
        ];

        return $data;
    }
}
