<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Block;

use Magento\Checkout\Block\Onepage\Success as CoreSuccess;
use Magento\Checkout\Model\Session;
use Magento\Framework\App\Http\Context as HttpContext;
use Magento\Framework\View\Element\Template\Context;
use Magento\Sales\Model\Order\Config;
use Shipay\PixQrGateway\Model\Traits\PaymentTrait;
use Shipay\PixQrGateway\Model\Wallet;

class Success extends CoreSuccess
{
    use PaymentTrait;

    /**
     * @var Wallet
     */
    private $wallet;

    /**
     * Success constructor.
     * @param Context $context
     * @param Session $checkoutSession
     * @param Config $orderConfig
     * @param HttpContext $httpContext
     * @param Wallet $wallet
     * @param array $data
     */
    public function __construct(
        Context $context,
        Session $checkoutSession,
        Config $orderConfig,
        HttpContext $httpContext,
        Wallet $wallet,
        array $data = []
    ) {
        parent::__construct($context, $checkoutSession, $orderConfig, $httpContext, $data);
        $this->wallet = $wallet;
    }

    /**
     * @return mixed|null
     */
    public function getPaymentAdditionalInformation()
    {
        $order = $this->_checkoutSession->getLastRealOrder();

        if (!$order) {
            return null;
        }

        $payment = $order->getPayment();

        if (!$payment) {
            return null;
        }

        return $payment->getAdditionalInformation();
    }
}
