<?php

declare(strict_types=1);

namespace Shipay\PixQrGateway\Model\Cache;

use Magento\Framework\App\Cache\Type\FrontendPool;
use Magento\Framework\Cache\Frontend\Decorator\TagScope;

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

class Type extends TagScope
{
    const TYPE_IDENTIFIER = 'shipay_token';
    const CACHE_TAG = 'SHIPAY_TOKEN';
    const CACHE_LIFE_TIME = 172800; // two days in seconds

    /**
     * Type constructor.
     * @param FrontendPool $cacheFrontendPool
     */
    public function __construct(
        FrontendPool $cacheFrontendPool
    ) {
        parent::__construct($cacheFrontendPool->get(self::TYPE_IDENTIFIER), self::CACHE_TAG);
    }
}
