<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Model\Ui;

use Magento\Checkout\Model\ConfigProviderInterface;
use Magento\Framework\View\Asset\Source;
use Magento\Payment\Model\CcConfig;
use Magento\Payment\Model\CcConfigProvider;
use Shipay\PixQrGateway\Api\WalletsRepositoryInterface;

class ConfigProvider extends CcConfigProvider implements ConfigProviderInterface
{
    const CODE = 'shipay';

    /**
     * @var WalletsRepositoryInterface
     */
    private $walletsRepository;

    /**
     * ConfigProvider constructor.
     * @param CcConfig $ccConfig
     * @param Source $assetSource
     * @param WalletsRepositoryInterface $walletsRepository
     */
    public function __construct(
        CcConfig $ccConfig,
        Source $assetSource,
        WalletsRepositoryInterface $walletsRepository
    ) {
        parent::__construct($ccConfig, $assetSource);
        $this->walletsRepository = $walletsRepository;
    }

    /**
     * @inheritDoc
     */
    public function getConfig()
    {
        $config = [
            'payment' => [
                self::CODE => [
                    WalletsRepositoryInterface::WALLETS => $this->walletsRepository->getWallets()
                ]
            ]
        ];

        return $config;
    }
}
