<?php

declare(strict_types=1);
/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2024 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Console\Command;

use Shipay\PixQrGateway\Gateway\StatusUpdater\Handler;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Psr\Log\LoggerInterface;

class UpdateStatusCommand extends Command
{

    /**
     * @var Handler
     */
    private $handler;

    /**
     * @var LoggerInterface
     */
    private $logger;

    /**
     * @param Handler $handler
     * @param LoggerInterface $logger
     * @param string|null $name
     */
    public function __construct
    (
        Handler $handler,
        LoggerInterface $logger,
        string $name = null
    ) {
        parent::__construct($name);
        $this->handler = $handler;
        $this->logger = $logger;
    }

    /**
     * @return void
     */
    protected function configure()
    {
        $this->setName('shipay:pix:update-orders')
            ->setDescription('Update Orders Status');
        parent::configure();
    }


    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        try {
            $updatedOrders = $this->handler->handle();
            $output->writeln('Shipay Update Orders Status Successfully.');
            $this->logger->debug("Shipay invoiced paid orders ids: $updatedOrders");
        } catch (\Exception $e) {
            $this->logger->error("Shipay UpdateOrderStatus Cli error: " . $e->getMessage());
        }
        return 0;
    }
}
