<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Cron;

use Shipay\PixQrGateway\Gateway\StatusUpdater\Handler;
use Psr\Log\LoggerInterface;

class UpdateOrderStatus
{
    /**
     * @var Handler
     */
    private $handler;

    /**
     * @var LoggerInterface
     */
    private $logger;

    /**
     * UpdateOrderStatus constructor.
     * @param Handler $handler
     * @param LoggerInterface $logger
     */
    public function __construct(
        Handler $handler,
        LoggerInterface $logger
    ) {
        $this->handler = $handler;
        $this->logger = $logger;
    }

    /**
     * @return void
     */
    public function execute()
    {
        try {
            $updatedOrders = $this->handler->handle();
            $this->logger->debug("Shipay invoiced paid orders ids: $updatedOrders");
        } catch (\Exception $e) {
            $this->logger->debug("Shipay UpdateOrderStatus Cron error: " . $e->getMessage());
        }
    }
}
