/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

define([
    'Magento_Checkout/js/view/payment/default',
    'underscore'
], function (Component, _) {
    'use strict';

    return Component.extend({
        defaults: {
            template: 'Shipay_PixQrGateway/payment/payment-form',
            wallet: ''
        },

        initObservable: function () {
            this._super().observe([
                'wallet',
            ]);

            return this;
        },

        getWallets: function() {
            return window.checkoutConfig.payment[this.getCode()].wallets;
        },

        getData: function () {
            return {
                'method': this.item.method,
                'additional_data': {
                    'wallet': this.wallet(),
                }
            };
        },

        getCode: function() {
            return 'shipay';
        },

        isShowLegend: function () {
            return true;
        },

        isAvailable: function () {
            return true;
        },

        isPlaceOrderActionAllowed: function() {
            return !!this.wallet().length;
        }
    });
});
