<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Gateway\StatusUpdater;

use Psr\Log\LoggerInterface as Logger;
use Shipay\PixQrGateway\Gateway\Config\Config;
use Shipay\PixQrGateway\Gateway\Enums\PaymentStatus;
use Shipay\PixQrGateway\Gateway\StatusUpdater\Model\Invoicer;
use Shipay\PixQrGateway\Gateway\StatusUpdater\Model\PaymentFinisher;
use Magento\Sales\Api\OrderManagementInterface;
class Handler
{
    /**
     * @var Client
     */
    private $client;

    /**
     * @var Invoicer
     */
    private $invoicer;

    /**
     * @var PaymentFinisher
     */
    private $paymentFinisher;

    /**
     * @var OrderManagementInterface
     */
    private $orderManagement;

    /**
     * @var Config
     */
    private $config;

    /**
     * @var Logger
     */
    private $logger;

    /**
     * Handler constructor.
     * @param Client $client
     * @param Invoicer $invoicer
     * @param PaymentFinisher $paymentFinisher
     * @param OrderManagementInterface $orderManagement
     * @param Config $config
     * @param Logger $logger
     */
    public function __construct(
        Client $client,
        Invoicer $invoicer,
        PaymentFinisher $paymentFinisher,
        OrderManagementInterface $orderManagement,
        Config $config,
        Logger $logger

    ) {
        $this->client = $client;
        $this->invoicer = $invoicer;
        $this->paymentFinisher = $paymentFinisher;
        $this->orderManagement = $orderManagement;
        $this->config = $config;
        $this->logger = $logger;
    }

    /**
     * @throws \Exception
     */
    public function handle()
    {
        $transactions = $this->client->placeRequest();

        if (empty($transactions)) {
            return false;
        }

        $updatedOrders = [];

        foreach ($transactions as $transaction) {
            $updatedOrders[] = $this->handleOrderUpdate($transaction);
        }

        return $this->getUpdatedOrders($updatedOrders);
    }

    /**
     * @param array $transaction
     * @return bool
     */
    public function handleOrderUpdate($transaction)
    {
        if (!isset($transaction['status']) ||
            !isset($transaction['payment_id']) ||
            !isset($transaction['order_id'])
        ) {
            return false;
        }

        if ($transaction['status'] === PaymentStatus::EXPIRED) {
            if ($this->config->allowedCancelOrders()) {
                $this->cancelOrder($transaction['order_id']);
            }
            $this->paymentFinisher->closePayment($transaction['payment_id'], $transaction['status']);
            return $transaction['order_id'];
        }

        if ($transaction['status'] === PaymentStatus::CANCELLED) {
            if ($this->config->allowedCancelOrders()) {
                $this->cancelOrder($transaction['order_id']);
            }
            $this->paymentFinisher->closePayment($transaction['payment_id'], $transaction['status']);
            return $transaction['order_id'];
        }

        if ($transaction['status'] === PaymentStatus::PAID) {
            $orderId = $this->invoicer->invoice($transaction['order_id']);
            $this->paymentFinisher->closePayment($transaction['order_id'], $transaction['status']);
            return $orderId;
        }

        return true;
    }


    /**
     * @param $orderId
     * @return mixed
     */
    private function cancelOrder($orderId)
    {
        try {
            $this->orderManagement->cancel($orderId);
            $this->logger->debug("Shipay Webhook Order Canceled : ". $orderId);
        } catch (\Exception $e) {
            $this->logger->debug("Shipay Webhook Error Cancel Order: ". $e->getMessage());
        }

        return $orderId;
    }

    /**
     * @param array $updatedOrders
     * @return string
     */
    private function getUpdatedOrders($updatedOrders)
    {
        $orders = '';
        foreach ($updatedOrders as $order) {
            if ($order) {
                $orders .= " $order ";
            }
        }

        return $orders;
    }
}
