<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Gateway\Converter;

interface ConverterInterface
{
    /**
     * Convert Money to cents or cents to money
     *
     * @param string|int|float $value
     * @return string|int|float
     */
    public function convert($value);
}
