<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 */

namespace Shipay\PixQrGateway\Gateway\Http;
use Shipay\PixQrGateway\Gateway\Http\Transactions;
class GetPaymentTransaction extends Transactions
{

    /**
     * @param $transactionId
     * @return bool
     * @throws \Exception
     */
    public function placeRequest($transactionId)
    {
        // phpcs:disable
        $channel = curl_init($this->urlResolver->getTransactionUrl($transactionId));
        return $this->requestShipay($channel);
    }
}
