<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 */

namespace Shipay\PixQrGateway\Gateway\StatusUpdater\Logger\Handler;

use Magento\Framework\Logger\Handler\System;

class Critical extends System
{
    /**
     * @var string
     */
    const DEFAULT_DEBUG_FILE_NAME = '/var/log/shipay_cron.log';

    /**
     * @var string
     */
    protected $fileName = self::DEFAULT_DEBUG_FILE_NAME;
}
