<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Controller\Adminhtml\Registration;

use Magento\Backend\App\Action;
use Magento\Backend\Model\View\Result\RedirectFactory;

class Index extends Action
{
    public const ADMIN_RESOURCE = 'Shipay_PixQrGateway::registration';

    /**
     * @var RedirectFactory
     */
    private $redirectFactory;

    /**
     * Index constructor.
     * @param Action\Context $context
     * @param RedirectFactory $redirectFactory
     */
    public function __construct(
        Action\Context $context,
        RedirectFactory $redirectFactory
    ) {
        parent::__construct($context);
        $this->redirectFactory = $redirectFactory;
    }

    /**
     * @inheritDoc
     */
    public function execute()
    {
        // phpcs:disable
        return $this->redirectFactory
            ->create()
            ->setUrl('https://pdv.shipay.com.br/gAAAAABgSD41wKYfETzwKQyAhQ95MzSZ60izLQN4ujE3tUU1cV5jVD9XSocTVGQoxZBRi_sNe1i-fp-t0fUhXpr3xEqyAv30xA==');
        // phpcs:enable
    }
}
