<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 */

namespace Shipay\PixQrGateway\Gateway\Response;

interface ResponseFieldsInterface
{
    const DEEP_LINK = 'deep_link';
    const ORDER_ID = 'order_id';
    const PIX_PSP = 'pix_psp';
    const QR_CODE = 'qr_code';
    const QR_CODE_TEXT = 'qr_code_text';
    const STATUS = 'status';
    const WALLET = 'wallet';
}
