<?php

declare(strict_types=1);

/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category Shipay
 * @package Shipay_PixQrGateway
 * @copyright Copyright (c) 2021 Shipay
 * @author Shipay <ajuda@shipay.com.br>
 *
 * See LICENSE for license details.
 */

namespace Shipay\PixQrGateway\Gateway\Enums;

class PaymentStatus
{
    const PENDING_PAYMENT = 'pending';
    const PAID = 'approved';
    const EXPIRED = 'expired';
    const CANCELLED = 'cancelled';
    const REFUNDED = 'refunded';
    const PARTIAL_REFUNDED = 'partial_refunded';
}
